### ISSUE TITLE
Can we have tags for groups of 10?

### ISSUE THREAD

**Issue by jasonwilliams** [remiberthoz/anki-periodic-table-memory-pegs#127]
Sometimes I want to learn cards from 1-10 or the set from 40-50 before moving on, it would be nice if there were tags for this

**Comment by remiberthoz** [comment]
That's a good idea. I suppose we could tags by periods instead of groups of ten: what do you think?

**Comment by jasonwilliams** [comment]
> That's a good idea. I suppose we could tags by periods instead of groups of ten: what do you think?

I’m ok with that 👍

**Comment by remiberthoz** [comment]
This was done in commit 8ff15735880b978f0d5b0ffce2b8378d1de920e4 ! I added tags for groups and periods :smile:. AnkiWeb is having an issue right now. I will update the deck there when the websites comes back.
