### ISSUE TITLE
Calcium: Picture for 20 reminds me of teeth, which might be a better option for Calcium?

### ISSUE THREAD

**Issue by kevfrost** [remiberthoz/anki-periodic-table-memory-pegs#128]
Calcium is often represented by bones or teeth, might it be better to have a mouth full of 20 teeth for this one?

**Comment by remiberthoz** [comment]
Hey, thanks for your input :smile: ! That sound like a good idea. I don't have much time to take care of modifications right now, but if you feel like creating an illustration I will be happy to merge it.

**Comment by horwitz** [comment]
major changes in existing mnemonics (esp. the Pratt ones) that many of us have been using for many years could be troublesome to say the least

**Comment by remiberthoz** [comment]
Indeed, in this case it would work to slightly alter the sentence by saying
this is a necklace of teeth, instead of pearls?

**Comment by horwitz** [comment]
that's certainly a less-dramatic change (IMO)

(I'd say that the image doesn't really look at all like teeth, but these are so low-res 🤷‍♀️)

**Comment by remiberthoz** [comment]
I updated the deck as discussed here. Thanks for the suggestion!
