### ISSUE TITLE
Chlorine: Clorox not familiar to UK users

### ISSUE THREAD

**Issue by kevfrost** [remiberthoz/anki-periodic-table-memory-pegs#129]
As with all mnemonics, it's important to link the item to something familiar.  Clorox is unknown in the UK, so might limit the universality of the cards?

**Comment by remiberthoz** [comment]
Hi, thanks! :smile: I'm from the EU myself, and I agree that many cards are not universal enough. I wish I had ideas to update each of them. I would be very happy to update the deck with suggestions.
