### ISSUE TITLE
Mnemonic for Flerovium idea

### ISSUE THREAD

**Issue by jcznk** [remiberthoz/anki-periodic-table-memory-pegs#131]
Amphitheatrum **Fl**avium (aka the Colosseum), popular around **114** a.D.
Some dates: 
70 or 72 (construction) - 80 (inauguration) - 6th century or 523 a.D. (last exhibition)
The element Flerovium is named after Georgij **Fl**ërov, a soviet nuclear physicist 

![image](https://user-images.githubusercontent.com/60730312/145109653-dbc62cff-7a2b-4bf8-a4e4-dfe1bfaf3bf3.png)

(disclaimer: I do not own the image; only illustrative)

**Comment by jcznk** [comment]
Maybe something like

![image](https://user-images.githubusercontent.com/60730312/145111537-2d2fa0d5-33b4-4c31-8d35-df4812dd8c56.png)

**Comment by remiberthoz** [comment]
Hi, I like the idea!

We would need to design the coliseum image in a 32x32 pixel art; I would love it if the 114 were embedded in the illustration, as you did. Would you like to try?

**Comment by jcznk** [comment]
I would like to, unfortunately I have zero experience in illustration. I still might try! (when I'll have some more free time)

**Comment by remiberthoz** [comment]
Pull request #133 suggested memory pegs for elements 114. Since pictures were provided, I implemented the changes.

Thanks for your contribution anyway!
