### ISSUE TITLE
Ideas for Roentgenium and Oganesson

### ISSUE THREAD

**Issue by jcznk** [remiberthoz/anki-periodic-table-memory-pegs#132]
Hello, it's me again.
These are the mnemonics I am using at the moment for:
Roentgenium (111) 
![image](https://user-images.githubusercontent.com/60730312/154816126-b06cc8bd-5243-4bc8-814c-1a0bf4645f8e.png) 
and Oganesson (118) 
 ![paste-d6d4cec80d427c98ac9357051bfc56881027d18f](https://user-images.githubusercontent.com/60730312/154816067-432d7799-d976-4025-80c3-3b19eb9cdcef.jpg)

Roentgenium is named after Wilhelm Röntgen, the guy who discovered x-rays. The photo is an x-ray of his wife's hand. The fingers resemble the number 1, hence 1 1 1 = 111

The second picture is a drawing of Yuri Oganessian, after which Oganesson is named. The wrinkles on the forehead and the glasses kind of resemble the number 118, tilted.

**Comment by jcznk** [comment]
(I tried creating a 32x32 pixel art of the Colosseum for Flerovium's mnemonic, but without much success.
Mostly because I couldn't recreate a decent enough image of the Colosseum under 64x64 pixels.
I might try again when I'll have some more time!)

**Comment by remiberthoz** [comment]
Pull request #133 suggested memory pegs for elements 111 and 118. Since pictures were provided, I implemented the changes.

Thanks for your contribution anyway!
