### ISSUE TITLE
Spelling issues

### ISSUE THREAD

**Issue by davidmwolf** [remiberthoz/anki-periodic-table-memory-pegs#2]
I'm not a dev or I'd fix it myself.

For oxygen (8), "Lifepreservers" should be two words: "Life preservers" or "Life-preservers"
For magnesium (12), "filledwith" should be two words: "filled with"
For krypton (36), "Kryptonn gas" (two n's) should be "Krypton gas"
Also for krypton, it is no longer true (as of 1983) that krypton defines the meter.

**Comment by remiberthoz** [comment]
Thank you for reporting this mistakes, I will fix them in the coming week.
I will clarify on the card that krypton is no longer used to define the
meter. Thanks !

**Comment by remiberthoz** [comment]
Thanks again for reporting the mistakes! They are fixed in v2.1.2.
